### ISSUE TITLE
Cannot join the server with Runes of Wizardry installed

### ISSUE THREAD

**Issue by belathus** [Xilef11/Runes-of-Wizardry#16] opened 2016-05-14 18:32 UTC
I saw a line when attempting to join my server below; I removed Runes of Wizardry and attempted to join again successfully. It seems there is also an infinite ArrayIndexOutOfBounds error that happens right after that kills my log file; the log is 42mb long. I snipped out a relevant section in a pastebin, but I can send you more if you need it.

Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Load@69756683:
java.lang.ArrayIndexOutOfBoundsException: 0
    at net.minecraft.server.MinecraftServer.func_130014_f_(MinecraftServer.java:1233) ~[MinecraftServer.class:?]
    at xilef11.mc.runesofwizardry_classics.runes.RuneResurrection.initDropsTable(RuneResurrection.java:94) ~[RuneResurrection.class:?]

http://pastebin.com/pUhgaV1E

**Comment by Xilef11** [comment] 2016-05-14 19:46
Version of Forge and both mods (Runes of Wizardry and classic dusts pack) ?
dedicated server crash or client crash?

**Comment by belathus** [comment] 2016-05-15 17:41
Yes, both mods. Forge version 1890.

**Comment by belathus** [comment] 2016-05-15 17:42
And, dedicated server. There was no crash, I was just unable to join the server.

**Comment by Xilef11** [comment] 2016-05-15 17:54
- which version of the mods? also, what is the full Forge (and minecraft) version (i.e 1.9-XXX or 1.8.9-xxx)

**Comment by Divineaspect** [comment] 2016-05-20 20:11
Runes of Wizardry 0.6.0
Classic Dusts Pack 0.2

**Comment by Xilef11** [comment] 2016-05-21 00:36
[note to self] caused by [this code](https://github.com/Xilef11/runesofwizardry-classics/blob/v1.8.9-0.2/src/main/java/xilef11/mc/runesofwizardry_classics/runes/RuneResurrection.java#L94), because client (w/ dedicated server) does not have a local world. running server side only should fix that.

**Comment by Xilef11** [comment] 2016-05-22 15:03
Fixed in runesofwizardry-classic (Classic Dust Pack) [v0.2.1](https://github.com/Xilef11/runesofwizardry-classics/releases/tag/v1.8.9-0.2.1)

**Closed as completed by Xilef11** 2016-05-22 15:03 UTC
