### ISSUE TITLE
Server time out in TileEntityDustDead

### ISSUE THREAD

**Issue by LemADEC** [Xilef11/Runes-of-Wizardry#53] opened 2019-12-21 00:23 UTC
As of Runes-of-Wizardry-1.12.2-0.9.2, servers times out when updating TileEntityDustDead due to a dead lock in the update code.
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 300.00 seconds (should be max 0.05)
        at com.zpig333.runesofwizardry.tileentity.TileEntityDustDead.func_73660_a(TileEntityDustDead.java:34)
        at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
        at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4728)
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zll000(WorldServer.java:4712)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hendersont2** [comment] 2020-04-17 14:53
I have this same issue. Any workarounds?

**Comment by Xilef11** [comment] 2020-04-23 13:39
Sorry for the delay. I can't reproduce this issue or figure out why it would happen, but commit [f7ae11456](https://github.com/Xilef11/Runes-of-Wizardry/commit/f7ae114563f38e661e69093523ca0b6aeeb5ce49) should remove any potential infinite loop in that code. Will be in the next release

**Closed as completed** 2020-04-23 13:38 UTC
